#!/usr/bin/env python3
"""
Generate config.js from .env file for browser usage.

This script reads .env file and generates a config.js file that can be
loaded by the browser application.

Usage:
    python scripts/generate-config.py
"""

import os
from pathlib import Path


def load_env_file(env_path: Path) -> dict:
    """Load .env file and return as dictionary."""
    config = {}
    
    if not env_path.exists():
        print(f"Warning: {env_path} not found")
        return config
    
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            # Parse KEY=VALUE
            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # Remove quotes if present
                if value.startswith('"') and value.endswith('"'):
                    value = value[1:-1]
                elif value.startswith("'") and value.endswith("'"):
                    value = value[1:-1]
                
                config[key] = value
    
    return config


def generate_config_js(config: dict, output_path: Path):
    """Generate config.js file from config dictionary."""
    
    # Start with warning comment
    js_content = [
        "/**",
        " * AUTO-GENERATED CONFIG FILE",
        " * ",
        " * This file is generated from .env by scripts/generate-config.py",
        " * DO NOT EDIT THIS FILE DIRECTLY - Edit .env instead",
        " * ",
        " * To regenerate: python scripts/generate-config.py",
        " */",
        "",
        "window.ENV_CONFIG = {",
    ]
    
    # Add each config entry
    for key, value in config.items():
        # Convert to JavaScript format
        if value.lower() in ('true', 'false'):
            js_value = value.lower()
        elif value.isdigit():
            js_value = value
        else:
            # Escape quotes in string values
            escaped_value = value.replace("'", "\\'")
            js_value = f"'{escaped_value}'"
        
        js_content.append(f"  {key}: {js_value},")
    
    js_content.append("};")
    js_content.append("")
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(js_content))
    
    print(f"✅ Generated {output_path}")


def main():
    # Get project root directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    # Paths
    env_path = project_root / '.env'
    output_path = project_root / 'config.js'
    
    print(f"📖 Reading {env_path}")
    config = load_env_file(env_path)
    
    if not config:
        print("⚠️  No configuration found in .env file")
        print("💡 Copy .env.example to .env and fill in your API keys")
        return
    
    print(f"📝 Found {len(config)} configuration entries")
    
    # Generate config.js
    generate_config_js(config, output_path)
    
    # Check for sensitive keys
    sensitive_keys = ['GEMINI_API_KEY', 'OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'MAPBOX_ACCESS_TOKEN']
    configured_keys = [key for key in sensitive_keys if config.get(key)]
    missing_keys = [key for key in sensitive_keys if not config.get(key)]
    
    if configured_keys:
        print(f"\n✅ Configured API keys: {', '.join(configured_keys)}")
    
    if missing_keys:
        print(f"\n⚠️  Optional API keys not set: {', '.join(missing_keys)}")
        print("💡 Add them to .env file if needed")
    
    # Check LLM provider
    llm_provider = config.get('LLM_PROVIDER', 'gemini')
    print(f"\n🤖 LLM Provider: {llm_provider}")
    
    if llm_provider == 'gemini' and config.get('GEMINI_API_KEY'):
        print("✅ Gemini API configured (FREE!)")
    elif llm_provider == 'openai' and config.get('OPENAI_API_KEY'):
        print("✅ OpenAI API configured")
    elif llm_provider == 'anthropic' and config.get('ANTHROPIC_API_KEY'):
        print("✅ Anthropic API configured")
    else:
        print(f"⚠️  {llm_provider.upper()}_API_KEY not set - LLM features will use fallback")
    
    print(f"\n🔒 Remember to add config.js to .gitignore!")


if __name__ == '__main__':
    main()
